volumes:
  pg_data_production:
  static_volume:

services:
  db:
    image: postgres:13.10
    env_file: .env
    volumes:
      - pg_data_production:/var/lib/postgresql/data
  backend:
    image: semo18/taski_backend
    platform: linux/amd64
    env_file: .env
    volumes:
      - static_volume:/backend_static
  frontend:
    image: semo18/taski_frontend  # Используем правильный логин
    platform: linux/amd64
    env_file: .env
    command: cp -r /app/build/. /frontend_static/
    volumes:
      - static_volume:/frontend_static
  gateway:
    image: semo18/taski_gateway  # Используем правильный логин
    platform: linux/amd64
    env_file: .env
    volumes:
      - static_volume:/staticfiles/
    ports:
      - 8000:80
